title: Carte de Fougères Agglomération
flow:
  svg: "https://raw.githubusercontent.com/Xinoje/Carte-de-L-agglom-ration/main/point_test.svg"
options:
  theme: light
  zoom:
    enabled: true
    min: 0.1
    max: 10
